apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: the-project
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - image: ssantos94/the_project:bawbh90
        name: todo-app