apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: the-project
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: todo-app
        image: docker.io/ssantos94/the_project:q3974hn
        env: 
          - name: PORT
            value: "9090"
          - name: GIN_MODE
            value: "release"