apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: the-project
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: project-storage
          persistentVolumeClaim:
            claimName: project-pvc
      containers:
      - name: project
        image: ssantos94/the_project:7GHW8V
        env: 
          - name: PORT
            value: "9090"
          - name: GIN_MODE
            value: "release"
        volumeMounts:
          - mountPath: /app/cache
            name: project-storage