apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: project-route
  namespace: project
spec:
  parentRefs:
  - name: my-gateway
    namespace: exercises
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /todos
    backendRefs:
    - name: the-project-svc
      port: 9091
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: the-project-svc
      port: 9090