apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: the-project-svc
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - name: http-frontend
      port: 9090
      targetPort: 9090
    - name: http-backend
      protocol: TCP
      port: 9091       # Service port
      targetPort: 9091 # Pod port
