apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/cm.yaml
  - manifests/pg.yaml
  - manifests/pvc.yaml
  - manifests/http-route.yaml
  - manifests/ns.yaml
  - manifests/cronjob.yaml

images:
  - name: PROJECT/IMAGE
    newName: ssantos94/the_project:hinmbse4