apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log-output
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: pingpong-volume
        persistentVolumeClaim:
          claimName: ping-pong-claim
      containers:
      - image: ssantos94/log-output:9nbW7hb8
        name: log-output-api
        command: ["./log-output"]
        args: ["api"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: pingpong-volume
          mountPath: /app/counter
      - image: ssantos94/log-output:9nbW7hb8
        name: log-output-random
        command: ["./log-output"]
        args: ["random"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
