apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  labels:
    app: log-output
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: config-map-volume
        configMap:
          name: log-output-cm
          items:
          - key: information.txt
            path: information.txt
      containers:
      - image: ssantos94/log-output:n9v9wb2
        name: log-output-api
        command: ["./log-output"]
        args: ["api"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: config-map-volume
          mountPath: /app/cm
        envFrom:
        - configMapRef:
            name: log-output-cm
      - image: ssantos94/log-output:n9v9wb2
        name: log-output-random
        command: ["./log-output"]
        args: ["random"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data


