apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      port: 8080
      targetPort: 9090